# -*- coding: utf-8 -*-
import logging

from odoo import api, fields, models, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

# Fields of worksheet.template.line that must follow the line when it is moved
# to another task. Anything not listed here is either recomputed, or belongs to
# the old task and must not be carried over.
LINE_FIELDS_TO_MOVE = [
    'name',
    'template_id',
    'select_user',
    'fleet_id',
    'done_mark',
    'line_add',
    'worksheet_id',
    'allow_worksheets',
    'fsm_is_sent',
    'food',
    'extra',
    'beverage',
    'transport',
    'other',
    'other_2',
    'other_3',
    'customer_signature',
    'customer_signed_by',
    'technician_signature',
    'technician_signed_by',
]


class TaskWizard(models.TransientModel):
    _name = 'task.wizard'
    _description = 'Field Service Task Wizard'

    def _default_task_tmpl(self):
        return self.env['project.task'].browse(self._context.get('active_id'))

    current_task_tmpl_id = fields.Many2one('project.task', default=_default_task_tmpl)
    help_desk_ticket_id = fields.Many2one('helpdesk.ticket', string="Select/Create Ticket")
    select_created_helpdesk_ticket = fields.Boolean('Select a  Helpdesk Ticket')
    name = fields.Char('Task name')
    partner_id = fields.Many2one('res.partner', 'Customer')

    @api.model
    def default_get(self, fields_list):
        res = super().default_get(fields_list)
        task = self._default_task_tmpl()
        if task and 'partner_id' in fields_list and not res.get('partner_id'):
            res['partner_id'] = task.partner_id.id
        return res

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _worksheet_host_field(self, line):
        """Name of the m2o on the generated worksheet model pointing at the host record.

        Worksheet models generated by `worksheet.template` name it
        ``x_<res_model_with_underscores>_id`` (e.g. ``x_project_task_id``).
        """
        res_model = (line.template_id.res_model or 'project.task').replace('.', '_')
        return 'x_%s_id' % res_model

    def _get_worksheets(self, line):
        """Return the generated worksheet record(s) attached to ``line``, if any."""
        model_name = line.template_id.model_id.model
        if not model_name or model_name not in self.env:
            return None
        return self.env[model_name].sudo().search([('x_studio_line_id', '=', line.id)])

    def _prepare_new_task_vals(self):
        self.ensure_one()
        source = self.current_task_tmpl_id
        task_fields = self.env['project.task']._fields
        vals = {
            'name': self.name,
            'partner_id': self.partner_id.id or source.partner_id.id,
            'project_id': source.project_id.id,
            'related_task': source.id,
        }
        if 'helpdesk_ticket_id' in task_fields:
            vals['helpdesk_ticket_id'] = source.helpdesk_ticket_id.id
        return vals

    def _prepare_moved_line_vals(self, line, new_task):
        vals = {'project_task_id': new_task.id, 'select_vals': False}
        for fname in LINE_FIELDS_TO_MOVE:
            if fname not in line._fields:
                continue
            field = line._fields[fname]
            vals[fname] = line[fname].id if field.type == 'many2one' else line[fname]
        vals['project_id'] = new_task.project_id.id
        return vals

    # ------------------------------------------------------------------
    # Main action
    # ------------------------------------------------------------------
    def action_task_view(self):
        self.ensure_one()
        source = self.current_task_tmpl_id
        if not source:
            raise UserError(_("The source task could not be found. Please reopen the task and try again."))

        lines = source.worksheet_template_lines.filtered(lambda l: l.select_vals)
        if not lines:
            raise UserError(_("Please tick at least one worksheet on the task before creating a new task."))

        done_lines = lines.filtered(lambda l: l.done_mark)
        if done_lines:
            raise UserError(_(
                "The following worksheet(s) are already marked as done and cannot be moved:\n%s",
                "\n".join("- %s" % line.display_name for line in done_lines)))

        new_task = self.env['project.task'].create(self._prepare_new_task_vals())

        moved = blank = 0
        for line in lines:
            worksheets = self._get_worksheets(line)
            new_line = self.env['worksheet.template.line'].create(
                self._prepare_moved_line_vals(line, new_task))

            if worksheets:
                host_field = self._worksheet_host_field(line)
                ws_vals = {'x_studio_line_id': new_line.id}
                if host_field in worksheets._fields:
                    ws_vals[host_field] = new_task.id
                try:
                    with self.env.cr.savepoint():
                        worksheets.sudo().write(ws_vals)
                except Exception:
                    # A stale unique(x_<model>_id) constraint may still exist on
                    # older generated worksheet models. Keep the line link so no
                    # data is lost rather than aborting the whole move.
                    _logger.warning(
                        "Could not re-point worksheet(s) %s to task %s; keeping line link only.",
                        worksheets.ids, new_task.id, exc_info=True)
                    worksheets.sudo().write({'x_studio_line_id': new_line.id})
                new_line.worksheet_id = worksheets[0].id
            else:
                # Nothing filled in yet: the line moves on its own and a worksheet
                # will be created on the new task the first time UPDATE is clicked.
                blank += 1
                new_line.line_add = False
                new_line.worksheet_id = False

            # Follow-on documents keep pointing at the worksheet they belong to.
            if line.expense_id:
                line.expense_id.sudo().write({
                    'expense_id_worksheet_line': new_line.id,
                    'task_id_rec': new_task.id,
                })
            purchases = self.env['purchase.order'].sudo().search(
                [('expense_id_worksheet_line', '=', line.id)])
            if purchases:
                purchases.write({
                    'expense_id_worksheet_line': new_line.id,
                    'worksheet_task_id': new_task.id,
                })
            moved += 1

        # Detach the old lines only once everything has been re-pointed.
        lines.unlink()
        # Clear any leftover ticks on the source task.
        source.worksheet_template_lines.filtered(lambda l: l.select_vals).write({'select_vals': False})

        body = _("%(moved)s worksheet(s) moved from %(source)s.",
                 moved=moved, source=source.display_name)
        if blank:
            body += " " + _("%(blank)s of them had no worksheet filled in yet.", blank=blank)
        new_task.message_post(body=body)
        source.message_post(body=_(
            "%(moved)s worksheet(s) moved to %(target)s.",
            moved=moved, target=new_task.display_name))

        action = {
            'type': 'ir.actions.act_window',
            'name': _('Task'),
            'res_model': 'project.task',
            'view_mode': 'form',
            'res_id': new_task.id,
            'target': 'current',
        }
        form_view = self.env.ref(
            'helpdesk_fsm.project_sharing_inherit_project_task_view_form', raise_if_not_found=False)
        if form_view:
            action['view_id'] = form_view.id
        return action
