{
    "name": "Restrict Record Deletion",
    "version": "19.0.1.2.0",
    "summary": "Remove the Delete action on Tickets, Tasks, Worksheets, Transfers, "
               "Quotations/Orders and Invoices for everyone except administrators",
    "description": """
Restrict Record Deletion
========================

Removes the ``Delete`` entry from the cog menu (and blocks the underlying
``unlink`` call) on:

* ``helpdesk.ticket``  - Helpdesk tickets
* ``project.task``     - Project / Field Service tasks
* ``sale.order``       - Quotations and sales orders
* ``account.move``     - Invoices, bills, credit notes, journal entries
* ``stock.picking``    - Deliveries, receipts and internal transfers
* worksheets           - every model generated by a ``worksheet.template``

It works purely through access rights: ``perm_unlink`` is cleared on every
``ir.model.access`` line of those models and re-granted through a dedicated
group that ``Settings / Administration`` implies. Odoo's
``ir.ui.view._postprocess_access_rights`` then sets ``delete="False"`` on the
view root for anyone without the unlink right, so the menu entry disappears on
its own - and the restriction also holds for RPC / XML-RPC / API calls.

Worksheet models are created at runtime, one per template, so they are
resolved from ``worksheet.template`` instead of being hard-coded, and the
restriction is re-applied whenever a new template is created.

Any further model - typically the worksheet/checklist model a custom module
embeds in the task form - can be added without editing code, through the
``vkd_restrict_delete.extra_models`` system parameter.

The module also overrides ``ir.ui.view._postprocess_access_rights`` so that a
view hard-coding ``delete="1"`` (which makes Odoo skip its own access-rights
check) cannot bring the trash icon back for users without the unlink right.

Line-level models (``sale.order.line``, ``account.move.line``, ``stock.move``,
``stock.move.line``) are deliberately untouched so users can still edit
documents normally.
""",
    "author": "VK DATA ApS",
    "website": "https://vkdata.dk/",
    "license": "OPL-1",
    "category": "Technical Settings",
    "depends": [
        "base",
        "sale",
        "account",
        "project",
        "helpdesk",
        "stock",
        "worksheet",
    ],
    "data": [
        "security/restrict_delete_groups.xml",
        "security/ir.model.access.csv",
        "data/restrict_delete_params.xml",
        "data/restrict_delete_apply.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
