import logging

from odoo import api, models, tools

_logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Models on which the Delete action must disappear for non-administrators.
# Add or remove entries here, then upgrade the module.
#
# NOTE: line models (sale.order.line, account.move.line, stock.move,
# stock.move.line) are intentionally NOT listed - removing unlink there would
# stop users from deleting the lines of a document they are still working on.
# ---------------------------------------------------------------------------
RESTRICTED_MODELS = [
    "helpdesk.ticket",   # Helpdesk tickets
    "project.task",      # Project and Field Service tasks
    "sale.order",        # Quotations and sales orders
    "account.move",      # Invoices, bills, credit notes, journal entries
    "stock.picking",     # Deliveries, receipts, internal transfers
]

# Worksheet records do not live in a fixed model: Odoo generates one model per
# worksheet.template at runtime (x_worksheet_...), so they can be listed
# neither above nor in security/ir.model.access.csv. They are resolved from
# the database instead - set this to False to leave worksheets alone.
RESTRICT_WORKSHEETS = True

# Any further model can be added without touching this file, through
# Settings > Technical > Parameters > System Parameters. Comma- or
# newline-separated list of technical model names, e.g.
#   kloudip.worksheet, x_worksheet_line
# Useful for the worksheet/checklist models that custom modules add to the
# task form: those are ordinary models with names this module cannot guess.
EXTRA_MODELS_PARAM = "vkd_restrict_delete.extra_models"

DELETE_GROUP_XMLID = "vkd_kloudip_restrict_delete.group_allow_record_deletion"
DELETE_GROUP_NAME = "group_allow_record_deletion"


class IrModelAccess(models.Model):
    _inherit = "ir.model.access"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    @api.model
    def _kloudip_delete_group(self):
        """The group that keeps the unlink right (empty recordset if absent)."""
        group = self.env.ref(DELETE_GROUP_XMLID, raise_if_not_found=False)
        if not group:
            # Tolerate the module folder being renamed: fall back to the xmlid
            # name alone.
            imd = self.env["ir.model.data"].sudo().search([
                ("model", "=", "res.groups"),
                ("name", "=", DELETE_GROUP_NAME),
            ], limit=1)
            group = self.env["res.groups"].browse(imd.res_id) if imd \
                else self.env["res.groups"]
        return group

    @api.model
    def _kloudip_worksheet_models(self):
        """Names of the models generated by the worksheet templates.

        One model per template, created together with the template, so the
        list has to be read from the database rather than hard-coded.
        """
        if not RESTRICT_WORKSHEETS or "worksheet.template" not in self.env:
            return []
        Template = self.env["worksheet.template"].sudo()
        if "model_id" not in Template._fields:
            _logger.warning(
                "restrict_delete: worksheet.template has no model_id field, "
                "skipping worksheet models"
            )
            return []
        templates = Template.with_context(active_test=False).search([])
        return [name for name in templates.mapped("model_id.model") if name]

    @api.model
    def _kloudip_extra_models(self):
        """Model names configured through the system parameter."""
        raw = self.env["ir.config_parameter"].sudo().get_param(
            EXTRA_MODELS_PARAM, ""
        )
        names = []
        for chunk in (raw or "").replace("\n", ",").replace(";", ",").split(","):
            name = chunk.strip()
            if name:
                names.append(name)
        return names

    @api.model
    def _kloudip_restricted_models(self):
        """Static list + worksheet models + whatever the parameter adds."""
        names = list(RESTRICTED_MODELS)
        for name in self._kloudip_worksheet_models() + self._kloudip_extra_models():
            if name not in names:
                names.append(name)
        return names

    @api.model
    @tools.ormcache()
    def _kloudip_restricted_models_cached(self):
        """Same list, cached - this one is hit on every view rendering.

        The cache is dropped by ``_kloudip_apply_delete_restrictions``, which
        runs on install/upgrade, when a worksheet template is created and when
        the system parameter changes.
        """
        return tuple(self._kloudip_restricted_models())

    @api.model
    def _kloudip_ensure_grant(self, ir_model, group):
        """Make sure the delete group keeps unlink on ``ir_model``.

        The models in RESTRICTED_MODELS get their line from
        security/ir.model.access.csv; the worksheet models and the models
        added through the system parameter have no xmlid, so their line is
        created here.
        """
        Access = self.sudo()
        grant = Access.search([
            ("model_id", "=", ir_model.id),
            ("group_id", "=", group.id),
        ], limit=1)
        if not grant:
            _logger.info(
                "restrict_delete: granting unlink on %s to %s",
                ir_model.model, group.display_name,
            )
            Access.create({
                "name": "%s.delete.admin" % ir_model.model,
                "model_id": ir_model.id,
                "group_id": group.id,
                "perm_read": False,
                "perm_write": False,
                "perm_create": False,
                "perm_unlink": True,
            })
        elif not grant.perm_unlink:
            grant.perm_unlink = True

    @api.model
    def _kloudip_clear_caches(self):
        """Drop the ormcache above and the cached view archs."""
        registry = self.env.registry
        try:
            registry.clear_cache("default", "templates")
        except Exception:  # cache names differ between versions
            registry.clear_cache()

    # ------------------------------------------------------------------
    # Entry point
    # ------------------------------------------------------------------
    @api.model
    def _kloudip_apply_delete_restrictions(self):
        """Clear perm_unlink on every access line of the restricted models,
        except the lines that grant it to the deletion group.

        Called from data/restrict_delete_apply.xml, so it re-runs on every
        install *and* every upgrade of this module. That matters: upgrading a
        core module (e.g. ``-u sale``) reloads its own ir.model.access.csv and
        would otherwise silently restore the delete rights. It also runs after
        a new worksheet template is created and after the extra-models
        parameter is changed.
        """
        group = self._kloudip_delete_group()
        allowed_ids = group.ids
        Access = self.sudo()
        IrModel = self.env["ir.model"].sudo()

        for model_name in self._kloudip_restricted_models():
            ir_model = IrModel.search([("model", "=", model_name)], limit=1)
            if not ir_model:
                _logger.warning(
                    "restrict_delete: model %s not found, skipping", model_name
                )
                continue

            if group:
                self._kloudip_ensure_grant(ir_model, group)

            lines = Access.search([
                ("model_id", "=", ir_model.id),
                ("perm_unlink", "=", True),
            ])
            # group_id may be NULL (line granted to every user), which a
            # "not in" domain would not match - so filter in Python.
            lines = lines.filtered(lambda a: a.group_id.id not in allowed_ids)
            if lines:
                _logger.info(
                    "restrict_delete: clearing unlink on %s for groups %s",
                    model_name,
                    lines.mapped("group_id.display_name") or ["<all users>"],
                )
                lines.write({"perm_unlink": False})

        self._kloudip_clear_caches()
        return True

    # ------------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------------
    @api.model
    def _kloudip_check_delete_restrictions(self):
        """Log what is covered and who can still delete it.

        Run it from Settings > Technical > Automation > Server Actions (a
        Python action on ir.model.access) or from an odoo shell::

            env['ir.model.access']._kloudip_check_delete_restrictions()

        Anything reported as "still granted" is a model whose Delete button
        will still show up.
        """
        report = []
        IrModel = self.env["ir.model"].sudo()
        group = self._kloudip_delete_group()
        for model_name in self._kloudip_restricted_models():
            ir_model = IrModel.search([("model", "=", model_name)], limit=1)
            if not ir_model:
                report.append((model_name, "MODEL NOT FOUND"))
                continue
            lines = self.sudo().search([
                ("model_id", "=", ir_model.id),
                ("perm_unlink", "=", True),
            ]).filtered(lambda a: a.group_id.id not in group.ids)
            report.append((
                model_name,
                "restricted" if not lines else "still granted to %s" % (
                    lines.mapped("group_id.display_name") or ["<all users>"]
                ),
            ))
        for model_name, status in report:
            _logger.info("restrict_delete: %-40s %s", model_name, status)
        return report
